export const FETCH_LIST_OF_TODOS = 'FETCH_LIST_OF_TODOS'
export const FETCH_LIST_OF_TODOS_SUCCESS = 'FETCH_LIST_OF_TODOS_SUCCESS'
export const FETCH_LIST_OF_TODOS_FAILURE = 'FETCH_LIST_OF_TODOS_FAILURE'